train:
  batch_size: 16
  num_epochs: 200
  learning_rate: 0.0001

model:
  type: cnn_vit        # 'vit' 또는 'vit2' 또는 'cnn_vit'로 선택
  img_size: 244
  patch_size: 16
  num_classes: 4
  in_chans: 25
  dropout_rate: 0.5      # CNN/ViT 모두에 적용

data:
  preprocessed_dir: data/preprocessed_wave
  save_experiment_dir: experiments/wave_new/LOSO_subject01
  test_subject: subject01

